name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Test
        run: |
          npm test
      - name: Build
        run: |
          npm run build
      - name: Store
        uses: actions/upload-artifact@v3
        with:
          name: drylungs
          path: public
